# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  evently.api:
    build:
      context: "/Users/schalkpienaar/Schalk/Source/GitHub/schalkpienaar/modular-monolith/Evently"
      dockerfile: "src/API/Evently.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Evently.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "evently.api:dev"
    ports: []
    volumes:
    - "/Users/schalkpienaar/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/schalkpienaar/Schalk/Source/GitHub/schalkpienaar/modular-monolith/Evently/src/API/Evently.Api:/app:rw"
    - "/Users/schalkpienaar/Schalk/Source/GitHub/schalkpienaar/modular-monolith/Evently:/src:rw"
    working_dir: "/app"
